name: HeavenBoards CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./heavenboards

      - name: Lint
        run: npm run lint
        working-directory: ./heavenboards

      - name: Format check
        run: npm run format -- --check
        working-directory: ./heavenboards

      - name: Type checking
        run: npm run type-check
        working-directory: ./heavenboards

      - name: Run unit tests
        run: npm run test:unit
        working-directory: ./heavenboards

      - name: Build
        run: npm run build
        working-directory: ./heavenboards
